apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: Path to the Dockerfile to build
        default: ${inputs.resources.source.path}/Dockerfile

  outputs:
    resources:
      - name: builtImage
        type: image

  steps:
    - name: install
      image: gcr.io/cloud-builders/yarn
      args:
        - install
      workingDir: ${inputs.resources.source.path}

    - name: test
      image: gcr.io/cloud-builders/yarn
      args:
        - test
      env:
        - name: CI
          value: "true"
      workingDir: ${inputs.resources.source.path}

    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --context=${inputs.resources.source.path}
        - --destination=${outputs.resources.builtImage.url}