apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-2
spec:
  serviceAccount: build-bot
  pipelineRef:
    name: demo-pipeline
  resources:
    - name: source
      resourceRef:
        name: tekton-demo-git
    - name: image
      resourceRef:
        name: tekton-demo-image
