apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image

  params:
    - name: REACT_APP_DRINK
      type: string
      description: "Please choose a drink: lemonade or cocktail"
    - name: pathToYamlFile
      type: string
      description: Path to the manifest to apply

  tasks:
    - name: test-my-app
      taskRef:
        name: test-task
      resources:
        inputs:
          - name: source
            resource: source

    - name: build-my-app
      runAfter:
        - test-my-app
      taskRef:
        name: build-task
      resources:
        inputs:
          - name: source
            resource: source
        outputs:
          - name: builtImage
            resource: image
      params:
        - name: REACT_APP_DRINK
          value: ${params.REACT_APP_DRINK}

    - name: deploy-my-app
      taskRef:
        name: deploy-task
      resources:
        inputs:
          - name: source
            resource: source
          - name: image
            resource: image
            from:
              - build-my-app
      params:
        - name: pathToYamlFile
          value: ${params.pathToYamlFile}
