apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: Path to the Dockerfile to build
        default: ${inputs.resources.source.path}/Dockerfile
      - name: REACT_APP_DRINK
        type: string
        description: "Please choose a drink: lemonade or cocktail"

  outputs:
    resources:
      - name: builtImage
        type: image

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.10.0
      args:
        - --build-arg
        - REACT_APP_DRINK=${inputs.params.REACT_APP_DRINK}
        - --dockerfile
        - ${inputs.params.pathToDockerFile}
        - --context
        - ${inputs.resources.source.path}
        - --destination
        - ${outputs.resources.builtImage.url}
