apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: task-run-test
spec:
  serviceAccount: build-bot
  taskRef:
    name: test-task
  inputs:
    resources:
      - name: source
        resourceRef:
          name: tekton-demo-git
