apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-task
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: pathToYamlFile
        type: string
        description: Path to the manifest to apply
      - name: clusterZone
        type: string
        description: Kurbernetes cluster's zone
      - name: clusterName
        type: string
        description: Kurbernetes cluster's name
  steps:
    - name: kubectl-apply
      image: gcr.io/cloud-builders/kubectl
      args:
        - apply
        - -f
        - ${inputs.params.pathToYamlFile}
      env:
        - name: CLOUDSDK_COMPUTE_ZONE
          value: ${inputs.params.clusterZone}
        - name: CLOUDSDK_CONTAINER_CLUSTER
          value: ${inputs.params.clusterName}
