apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: knative-build-demo
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/khanhalice/knative-build-demo:build