apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: build-v1
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/khanh-alice/tekton-demo.git
      revision: master

  steps:
  - name: install
    image: gcr.io/cloud-builders/yarn:node-10.10.0
    args:
    - install

  - name: test
    image: gcr.io/cloud-builders/yarn:node-10.10.0
    args:
    - test
    env:
    - name: CI
      value: "true"

  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.10.0
    args:
    - --build-arg
    - REACT_APP_DRINK=lemonade
    - --destination
    - docker.io/khanhalice/tekton-demo:1.0
