apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: react-build-template
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: REACT_APP_DRINK
    description: "Please choose a drink: lemonade or cocktail"

  steps:
  - name: install
    image: gcr.io/cloud-builders/yarn:node-10.10.0
    args:
    - install

  - name: test
    image: gcr.io/cloud-builders/yarn:node-10.10.0
    args:
    - test
    env:
    - name: CI
      value: "true"

  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.10.0
    args:
    - --build-arg
    - REACT_APP_DRINK=${REACT_APP_DRINK}
    - --destination
    - ${IMAGE}
