apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: my-app-v1
  namespace: default
spec:
  template:
    metadata:
      name: my-app-v1
    spec:
      containers:
        - image: docker.io/khanhalice/my-app:v1
          ports:
            - containerPort: 80