apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  template:
    metadata:
      name: my-app-v1
    spec:
      containers:
        - image: docker.io/khanhalice/tekton-demo:1.0
          ports:
            - containerPort: 80
