apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  template:
    metadata:
      name: my-app-v2
    spec:
      containers:
        - image: docker.io/khanhalice/tekton-demo:1.0-tekton
          ports:
            - containerPort: 80
  traffic:
    - tag: current
      revisionName: my-app-v1
      percent: 80
    - tag: candidate
      revisionName: my-app-v2
      percent: 20